#!/bin/sh

choices="laptop\nlaptopdual\nVGA\nHDMI\nManual Selection"
chosen=$(echo "$choices" | dmenu -i -p "Select Display")

case "$chosen" in
	laptop) xrandr --output LVDS1 --auto --output VGA1 --off;;
	laptopdual) xrandr --output LVDS1 --auto --output VGA1 --auto \
	            --right-of LVDS1;;
	VGA) xrandr --output VGA1 --auto --output LVDS1 --off;;
	HDMI) xrandr --output HDMI1 --auto --output LVDS1 --off;;
	"Manual Selection") arandr;;
esac
