#!/bin/sh

mvn archetype:generate \
		-DgroupId=$1 \
		-DartifactId=$2 \
		-DarchetypeGroupId=org.apache.maven.archetypes \
		-DarchetypeArtifactId=maven-archetype-webapp \
    	-DinteractiveMode=false \
